name: Validate Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Modified files
        run: |
          echo 'steps.files.outputs.added=${{ steps.files.outputs.added }}'
          echo 'steps.files.outputs.modified=${{ steps.files.outputs.modified }}'
      - run: yarn --frozen-lockfile
      - run: yarn validate
